---
- hosts: all
  gather_facts: false

  vars:
    - snow_username: admin
    - snow_password: https://dev107597.service-now.com
    - snow_url: "{{  lookup('env', 'instance_url') }}"

  tasks:

  - name: check variables
    debug:
      msg: "{{ snow_url }}"

  - name: create a ticket in SNOW
    snow_record:
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_url }}"
      state: present
      data:
        short_description: "This is a test opened by Ansible"
        priority: 2
      table: change_request
    register: new_change_request
    