---
- hosts: all
  gather_facts: false

  tasks:

  - name: create a ticket in SNOW
    snow_record:
      username: "{{ username }}"
      password: "{{ password }}"
      instance: "{{ instance_url }}"
      state: present
      data:
        short_description: "This is a test opened by Ansible"
        priority: 2
      table: change_request
    register: new_change_request
    