---
- name: create a change request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_url }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
    type: standard
    state: new
    requested_by: "{{ snow_username }}"
    short_description: automated change request
    description: change request automated by ansible
    priority: moderate
    risk: low
    impact: low
    assignment_group: software
  register: change_ticket

  
- name: save change request number
  set_fact:
    ticket_num: "{{ change_ticket.record.number }}"

