---
# tasks file for create_change_request

- name: create a change_request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_url }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
    type: standard
    state: new
    requested_by: "{{ snow_username }}"
    short_description: automated change request
    description: change request automated by ansible
    priority: moderate
    risk: low
    impact: low