---
# tasks file for close_change_request

- name: Close change_request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_url }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
    state: closed
    close_code: "successful"
    close_notes: "Closed by automation"
    assignment_group: software
    number: "{{ ticket_num }}"
    